/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import domain.Persona;
import datos.PersonaDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import test.test_Manejo_Dao_Persona;


/**
 *
 * @author jorge
 */
public class Persona_VISTA extends javax.swing.JFrame {

    
    //LLAMADAS
    Menu men = new Menu();
    PersonaDAO personaDao = new PersonaDAO();
    DefaultTableModel modelo;
    int filas = 0;
    int id_select = 0;
    int Times_Agregado = 0;
    int Times_Actualizado = 0;
    int Times_Eliminado = 0;
    
    public Persona_VISTA() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Email");
        modelo.addColumn("Teléfono");
        this.TABLA_PERSONA.setModel(modelo);
        
        Mostrar_Datos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNombre_Persona = new javax.swing.JTextField();
        txtApellido_Persona = new javax.swing.JTextField();
        txt_Email_Persona = new javax.swing.JTextField();
        txtTelefono_Persona = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAceptar_P = new javax.swing.JButton();
        btnActualizar_P = new javax.swing.JButton();
        btnEliminar_P = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA_PERSONA = new javax.swing.JTable();
        btnRegresar_Persona = new javax.swing.JButton();
        lbl_ID = new javax.swing.JLabel();
        lbl_Eliminado = new javax.swing.JLabel();
        lbl_Actualizado = new javax.swing.JLabel();
        lbl_Agregado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PERSONA");

        txtNombre_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_PersonaActionPerformed(evt);
            }
        });

        txtTelefono_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefono_PersonaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido");

        jLabel4.setText("Email");

        jLabel5.setText("Teléfono");

        btnAceptar_P.setText("Agregar");
        btnAceptar_P.setActionCommand("btnAGREGAR");
        btnAceptar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_PActionPerformed(evt);
            }
        });

        btnActualizar_P.setText("Actualizar");
        btnActualizar_P.setActionCommand("btnACTUALIZAR");
        btnActualizar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_PActionPerformed(evt);
            }
        });

        btnEliminar_P.setText("Eliminar");
        btnEliminar_P.setActionCommand("btnEliminar");
        btnEliminar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_PActionPerformed(evt);
            }
        });

        TABLA_PERSONA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Apellido", "Email", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TABLA_PERSONA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_PERSONAMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TABLA_PERSONA);

        btnRegresar_Persona.setText("Regresar");
        btnRegresar_Persona.setActionCommand("btnRegresar");
        btnRegresar_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar_PersonaActionPerformed(evt);
            }
        });

        lbl_Eliminado.setText("0");

        lbl_Actualizado.setText("0");

        lbl_Agregado.setText("0");

        jLabel6.setText("Contador: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lbl_Agregado)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelefono_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtApellido_Persona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                                    .addComponent(txtNombre_Persona, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_ID))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txt_Email_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(lbl_Eliminado))
                                                    .addComponent(btnEliminar_P))))))
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAceptar_P)
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lbl_Actualizado))
                                    .addComponent(btnActualizar_P)))))
                    .addComponent(btnRegresar_Persona))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar_Persona)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Email_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono_Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar_P)
                    .addComponent(btnActualizar_P)
                    .addComponent(btnEliminar_P))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Agregado)
                    .addComponent(lbl_Actualizado)
                    .addComponent(lbl_Eliminado)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtNombre_Persona.getAccessibleContext().setAccessibleName("txt_Nombre");
        txtApellido_Persona.getAccessibleContext().setAccessibleName("txt_Apellido");
        txt_Email_Persona.getAccessibleContext().setAccessibleName("txt_Email");
        txt_Email_Persona.getAccessibleContext().setAccessibleDescription("");
        txtTelefono_Persona.getAccessibleContext().setAccessibleName("txt_Tel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Mostrar_Datos() throws SQLException{
        //Traer datos de SQL
        List<Persona> personas = personaDao.seleccionar();
        
         for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        
        for (int i = 0; i < personas.size(); i++) {
            String[] info = new String[5];
            info[0]= String.valueOf(personas.get(i).getIdPersona());
            info[1]= personas.get(i).getNombre();
            info[2]= personas.get(i).getApellido();
            info[3]= personas.get(i).getEmail();
            info[4]= personas.get(i).getTelefono();
            modelo.addRow(info);
        }
      
    }
    
    private void Agregar_Datos() throws SQLException{
        
      
        Persona insertarPersona = new Persona();
        
        insertarPersona.setNombre(txtNombre_Persona.getText());
        insertarPersona.setApellido(txtApellido_Persona.getText());
        insertarPersona.setEmail(txt_Email_Persona.getText());
        insertarPersona.setTelefono(txtTelefono_Persona.getText());

        {
            try {
                personaDao.insertar(insertarPersona);
            } catch (SQLException ex) {
                Logger.getLogger(test_Manejo_Dao_Persona.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Mostrar_Datos();
        
        txtNombre_Persona.setText("");
        txtApellido_Persona.setText("");
        txt_Email_Persona.setText("");
        txtTelefono_Persona.setText("");
    }
    
    private void Actualizar_Datos() throws SQLException{
        
        Persona actualizarPersona = new Persona();
        
        actualizarPersona.setIdPersona(Integer.parseInt(lbl_ID.getText()));
        actualizarPersona.setNombre(txtNombre_Persona.getText());
        actualizarPersona.setApellido(txtApellido_Persona.getText());
        actualizarPersona.setEmail(txt_Email_Persona.getText());
        actualizarPersona.setTelefono(txtTelefono_Persona.getText());
       
        
        {
            try {
                personaDao.actualizar(actualizarPersona);
            } catch (SQLException ex) {
                Logger.getLogger(test_Manejo_Dao_Persona.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
          Mostrar_Datos();
        
        txtNombre_Persona.setText("");
        txtApellido_Persona.setText("");
        txt_Email_Persona.setText("");
        txtTelefono_Persona.setText("");
        
    }
    
    private void Eliminar_Datos() throws SQLException{
        
        Persona eliminarPersona = new Persona();
        eliminarPersona.setIdPersona(Integer.parseInt(lbl_ID.getText()));
        
        {
            try {
                personaDao.eliminar(eliminarPersona);
            } catch (SQLException ex) {
                Logger.getLogger(test_Manejo_Dao_Persona.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
          Mostrar_Datos();
          
        lbl_ID.setText("");
        txtNombre_Persona.setText("");
        txtApellido_Persona.setText("");
        txt_Email_Persona.setText("");
        txtTelefono_Persona.setText("");
    }
    
    
    private void txtTelefono_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefono_PersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono_PersonaActionPerformed

    private void txtNombre_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_PersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_PersonaActionPerformed

    private void btnAceptar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_PActionPerformed
        try {
            // TODO add your handling code here:
            //AGREGAR
            Agregar_Datos();
        } catch (SQLException ex) {
            Logger.getLogger(Persona_VISTA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Times_Agregado++;
        lbl_Agregado.setText("" + Times_Agregado);
    }//GEN-LAST:event_btnAceptar_PActionPerformed

    private void btnActualizar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_PActionPerformed
        try {
            // TODO add your handling code here:
            //ACTUALIZAR
            Actualizar_Datos();
        } catch (SQLException ex) {
            Logger.getLogger(Persona_VISTA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Times_Actualizado++;
        lbl_Actualizado.setText("" + Times_Actualizado);
    }//GEN-LAST:event_btnActualizar_PActionPerformed

    private void btnEliminar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_PActionPerformed
        try {
            // TODO add your handling code here:
            //ELIMINAR
            Eliminar_Datos();
        } catch (SQLException ex) {
            Logger.getLogger(Persona_VISTA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Times_Eliminado++;
        lbl_Eliminado.setText("" + Times_Eliminado);
    }//GEN-LAST:event_btnEliminar_PActionPerformed

    private void btnRegresar_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar_PersonaActionPerformed
        // TODO add your handling code here:
        //REgresar
        
        men.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRegresar_PersonaActionPerformed

    private void TABLA_PERSONAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_PERSONAMouseClicked
        // TODO add your handling code here:
       filas = TABLA_PERSONA.getSelectedRow();
       
       //id_select= (int) TABLA_PERSONA.getValueAt(filas, 0);
       lbl_ID.setText(TABLA_PERSONA.getValueAt(filas, 0).toString());
       txtNombre_Persona.setText(TABLA_PERSONA.getValueAt(filas,1).toString());
       txtApellido_Persona.setText(TABLA_PERSONA.getValueAt(filas,2).toString());
       txt_Email_Persona.setText(TABLA_PERSONA.getValueAt(filas,3).toString());
       txtTelefono_Persona.setText(TABLA_PERSONA.getValueAt(filas,4).toString());
    }//GEN-LAST:event_TABLA_PERSONAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Persona_VISTA().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Persona_VISTA.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLA_PERSONA;
    private javax.swing.JButton btnAceptar_P;
    private javax.swing.JButton btnActualizar_P;
    private javax.swing.JButton btnEliminar_P;
    private javax.swing.JButton btnRegresar_Persona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Actualizado;
    private javax.swing.JLabel lbl_Agregado;
    private javax.swing.JLabel lbl_Eliminado;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JTextField txtApellido_Persona;
    private javax.swing.JTextField txtNombre_Persona;
    private javax.swing.JTextField txtTelefono_Persona;
    private javax.swing.JTextField txt_Email_Persona;
    // End of variables declaration//GEN-END:variables
}
