/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import domain.Usuario;
import datos.UsuarioDAO;
import domain.Persona;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import test.test_Manejo_Dao_Persona;
import test.test_Manejo_Dao_Usuario;

/**
 *
 * @author jorge
 */
public class Usuario_VISTA extends javax.swing.JFrame {

    UsuarioDAO usuarioDao = new UsuarioDAO();
    DefaultTableModel modelo;    
    int filas = 0;
    Menu men = new Menu();
     int Times_Agregado = 0;
    int Times_Actualizado = 0;
    int Times_Eliminado = 0;
    
    public Usuario_VISTA() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("Usuario");
        modelo.addColumn("Contraseña");
        this.TABLA_USUARIO.setModel(modelo);
        
        Mostrar_Datos();
    }
    
    public Usuario_VISTA(Menu men) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("Usuario");
        modelo.addColumn("Contraseña");
        this.TABLA_USUARIO.setModel(modelo);
        
        
        
        Mostrar_Datos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar_Usuario = new javax.swing.JButton();
        btnActualizar_Usuario = new javax.swing.JButton();
        btnEliminar_Usuario = new javax.swing.JButton();
        btnRegresar_USUARIO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre_Usuaio = new javax.swing.JTextField();
        txtContra_Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_USUARIO = new javax.swing.JTable();
        lbl_ID = new javax.swing.JLabel();
        lbl_Eliminado = new javax.swing.JLabel();
        lbl_Actualizado = new javax.swing.JLabel();
        lbl_Agregado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar_Usuario.setText("Agregar");
        btnAgregar_Usuario.setActionCommand("btnAgregar_USUARIO");
        btnAgregar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_UsuarioActionPerformed(evt);
            }
        });

        btnActualizar_Usuario.setText("Actualizar");
        btnActualizar_Usuario.setActionCommand("btn_Actualizar");
        btnActualizar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_UsuarioActionPerformed(evt);
            }
        });

        btnEliminar_Usuario.setText("Eliminar");
        btnEliminar_Usuario.setActionCommand("btnELIMINAR");
        btnEliminar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_UsuarioActionPerformed(evt);
            }
        });

        btnRegresar_USUARIO.setText("Regresar");
        btnRegresar_USUARIO.setActionCommand("btnRegresar");
        btnRegresar_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar_USUARIOActionPerformed(evt);
            }
        });

        jLabel1.setText("USUARIO ");

        txtNombre_Usuaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_UsuaioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Usuario");

        jLabel3.setText("Contraseña");

        TABLA_USUARIO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Contaseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TABLA_USUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_USUARIOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLA_USUARIO);

        lbl_Eliminado.setText("0");

        lbl_Actualizado.setText("0");

        lbl_Agregado.setText("0");

        jLabel6.setText("Contador: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6)
                                .addGap(85, 85, 85)
                                .addComponent(lbl_Agregado)
                                .addGap(93, 93, 93)
                                .addComponent(lbl_Actualizado)
                                .addGap(82, 82, 82)
                                .addComponent(lbl_Eliminado))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnRegresar_USUARIO)
                                    .addGap(111, 111, 111)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(95, 95, 95)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNombre_Usuaio, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtContra_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(25, 25, 25)
                                    .addComponent(lbl_ID))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnAgregar_Usuario)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnActualizar_Usuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEliminar_Usuario)
                                    .addGap(55, 55, 55))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar_USUARIO)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre_Usuaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_ID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContra_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar_Usuario)
                    .addComponent(btnActualizar_Usuario)
                    .addComponent(btnEliminar_Usuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Agregado)
                    .addComponent(lbl_Actualizado)
                    .addComponent(jLabel6)
                    .addComponent(lbl_Eliminado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtNombre_Usuaio.getAccessibleContext().setAccessibleName("txt_Usuario");

        getAccessibleContext().setAccessibleName("txt_Contra");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombre_UsuaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_UsuaioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_UsuaioActionPerformed

    private void btnAgregar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_UsuarioActionPerformed
       try {
           // TODO add your handling code here:
           //Agregar
           Agregar_Datos();
       } catch (SQLException ex) {
           Logger.getLogger(Usuario_VISTA.class.getName()).log(Level.SEVERE, null, ex);
       }
       Times_Agregado++;
        lbl_Agregado.setText("" + Times_Agregado);
    }//GEN-LAST:event_btnAgregar_UsuarioActionPerformed

    private void btnActualizar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_UsuarioActionPerformed
       try {
           // TODO add your handling code here:
           //actualizar
           Actualizar_Datos();
       } catch (SQLException ex) {
           Logger.getLogger(Usuario_VISTA.class.getName()).log(Level.SEVERE, null, ex);
       }
       Times_Actualizado++;
        lbl_Actualizado.setText("" + Times_Actualizado);
    }//GEN-LAST:event_btnActualizar_UsuarioActionPerformed

    private void btnEliminar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_UsuarioActionPerformed
       try {
           // TODO add your handling code here:
           //eliminar
           Eliminar_Datos();
       } catch (SQLException ex) {
           Logger.getLogger(Usuario_VISTA.class.getName()).log(Level.SEVERE, null, ex);
       }
       Times_Eliminado++;
        lbl_Eliminado.setText("" + Times_Eliminado);
    }//GEN-LAST:event_btnEliminar_UsuarioActionPerformed

    private void TABLA_USUARIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_USUARIOMouseClicked
        filas = TABLA_USUARIO.getSelectedRow();

       lbl_ID.setText(TABLA_USUARIO.getValueAt(filas, 0).toString());
       txtNombre_Usuaio.setText(TABLA_USUARIO.getValueAt(filas,1).toString());
       txtContra_Usuario.setText(TABLA_USUARIO.getValueAt(filas,2).toString());
    }//GEN-LAST:event_TABLA_USUARIOMouseClicked

    private void btnRegresar_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar_USUARIOActionPerformed
        // TODO add your handling code here:
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar_USUARIOActionPerformed

    private void Mostrar_Datos() throws SQLException{
        //Traer datos de SQL
        List<Usuario> usuarios = usuarioDao.seleccionar();
        
         for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        
        for (int i = 0; i < usuarios.size(); i++) {
            String[] info = new String[5];
            info[0]= String.valueOf(usuarios.get(i).getidUsuario());
            info[1]= usuarios.get(i).getUsuario();
            info[2]= usuarios.get(i).getPassword();
            modelo.addRow(info);
        }
      
    }
    
    private void Agregar_Datos() throws SQLException{

        Usuario insertarUsuario = new Usuario();
        
        insertarUsuario.setUsuario(txtNombre_Usuaio.getText());
        insertarUsuario.setPassword(txtContra_Usuario.getText());

        {
            try {
                usuarioDao.insertar(insertarUsuario);
            } catch (SQLException ex) {
                Logger.getLogger(test_Manejo_Dao_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Mostrar_Datos();
        
        lbl_ID.setText("");
        txtNombre_Usuaio.setText("");
        txtContra_Usuario.setText("");
    }
    private void Actualizar_Datos() throws SQLException{
        
        Usuario actualizarUsuario = new Usuario();
        
        actualizarUsuario.setId_usuario(Integer.parseInt(lbl_ID.getText()));
        actualizarUsuario.setUsuario(txtNombre_Usuaio.getText());
        actualizarUsuario.setPassword(txtContra_Usuario.getText());
        {
            try {
                usuarioDao.actualizar(actualizarUsuario);
            } catch (SQLException ex) {
                Logger.getLogger(test_Manejo_Dao_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        Mostrar_Datos();
        
        lbl_ID.setText("");
        txtNombre_Usuaio.setText("");
        txtContra_Usuario.setText("");
        
    }
    
    private void Eliminar_Datos() throws SQLException{
        
        Usuario eliminarUsuario = new Usuario();
        eliminarUsuario.setId_usuario(Integer.parseInt(lbl_ID.getText()));
        
        {
            try {
                usuarioDao.eliminar(eliminarUsuario);
            } catch (SQLException ex) {
                Logger.getLogger(test_Manejo_Dao_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
          Mostrar_Datos();
          
        lbl_ID.setText("");
        txtNombre_Usuaio.setText("");
        txtContra_Usuario.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Usuario_VISTA().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Usuario_VISTA.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLA_USUARIO;
    private javax.swing.JButton btnActualizar_Usuario;
    private javax.swing.JButton btnAgregar_Usuario;
    private javax.swing.JButton btnEliminar_Usuario;
    private javax.swing.JButton btnRegresar_USUARIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Actualizado;
    private javax.swing.JLabel lbl_Agregado;
    private javax.swing.JLabel lbl_Eliminado;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JTextField txtContra_Usuario;
    private javax.swing.JTextField txtNombre_Usuaio;
    // End of variables declaration//GEN-END:variables
}
